#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
Pin a small set of must-exist nodes and edges produced by the extract / auto-discover pipeline. After any extractor change, this script asserts the pins still resolve. Catches silent extractor regressions.

.DESCRIPTION
Why this exists:
  The graph is generated by extract-code-graph.ps1 (code graph) +
  auto-discover-features.ps1 (system graph augmentation). Both are
  heuristic-driven. A change to either can silently drop entire
  categories of nodes or edges. Today's gates would not catch this:

    - JSON validity:        passes (output is well-formed)
    - Dangling edges:       passes (anything missing is gone, not dangling)
    - Health check:         passes (no orphans, no islands among what remains)

  This script pins specific contract-shape nodes and edges that MUST exist
  if the extractor is doing its job. Each pin includes a reason — when a
  pin breaks, the message tells you which extractor capability regressed.

  Pin philosophy:
    - Pin SHAPES not COUNTS. "code-func nodes exist for Mentor.agent.md"
      (shape) — not "exactly 178 code-func nodes" (count, churns).
    - Pin CONTRACTS, not implementation details. "every .agent.md gets a
      code-yaml-field:*::skills node when frontmatter has a skills array"
      is a contract; "node id matches regex X" is implementation.
    - Pin SAMPLES, not full coverage. We pick 1-2 representative inputs
      per extractor capability. The audit isn't full coverage; it's a
      tripwire.

How to add a pin:
  1. Identify a capability that, if it regressed silently, would be bad.
  2. Find the canonical input file that exercises it.
  3. Add an entry to $pins with: { Name; Reason; Assertion (script block returning $true/$false); Hint }
  4. Re-run; new pin should pass on current graph.

.PARAMETER Quiet
Print one-line summary only.

.EXAMPLE
pwsh .github/knowledge-graph/cli/tests/test-extractor-stability.ps1
pwsh .github/knowledge-graph/cli/tests/test-extractor-stability.ps1 -Quiet

.OUTPUTS
Exit 0 = all pins held. Exit 1 = at least one pin broke. Exit 2 = setup error.
#>
[CmdletBinding()]
param(
    [Parameter()]
    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = git rev-parse --show-toplevel 2>$null
if (-not $repoRoot -or $LASTEXITCODE -ne 0) {
    Write-Host "Not in a git repository." -ForegroundColor Red
    exit 2
}
$repoRoot = $repoRoot.TrimEnd('/', '\')

$mergedFile = Join-Path $repoRoot ".github/knowledge-graph/output/merged-graph.json"
if (-not (Test-Path $mergedFile)) {
    Write-Host "Merged graph not found." -ForegroundColor Red
    exit 2
}

$graph = Get-Content $mergedFile -Raw | ConvertFrom-Json

# Index helpers.
$nodesById = @{}
foreach ($n in $graph.nodes) { $nodesById[$n.id] = $n }

function Test-NodeExists {
    param([string]$Id)
    return $nodesById.ContainsKey($Id)
}

function Test-EdgeExists {
    param([string]$Source, [string]$Target, [string]$Type)
    foreach ($e in $graph.edges) {
        if ($e.source -eq $Source -and $e.target -eq $Target -and $e.type -eq $Type) {
            return $true
        }
    }
    return $false
}

function Test-NodeOfType {
    param([string]$Type, [int]$MinCount = 1)
    $count = @($graph.nodes | Where-Object { $_.type -eq $Type }).Count
    return $count -ge $MinCount
}

function Test-ChildNodes {
    param([string]$ParentId, [int]$MinCount)
    $count = @($graph.edges | Where-Object { $_.source -eq $ParentId -and $_.type -eq 'contains' }).Count
    return $count -ge $MinCount
}

# Pin set. Each pin asserts something the extract pipeline MUST produce
# if its capability is intact. The Hint tells you what extractor module
# probably broke if the pin fails.
$pins = @(
    @{
        Name      = 'Mentor agent node exists'
        Reason    = 'agent:mentor is the system root; if missing, every downstream query breaks.'
        Assertion = { Test-NodeExists 'agent:mentor' }
        Hint      = 'Check auto-discover-features.ps1 for agent discovery from .agent.md files.'
    },
    @{
        Name      = 'Mentor agent has its code-file node'
        Reason    = 'Hand-authored nodes need their backing file to also be in the graph (used by find-missing-files audit).'
        Assertion = { Test-NodeExists 'code-file:.github/agents/Mentor.agent.md' }
        Hint      = 'Check extract-code-graph.ps1 markdown discovery.'
    },
    @{
        Name      = 'YAML frontmatter fields extracted from Mentor.agent.md'
        Reason    = 'Frontmatter is the agent contract; if not extracted, contract drift goes undetected.'
        Assertion = { Test-NodeExists 'code-yaml-field:.github/agents/Mentor.agent.md::skills' }
        Hint      = 'Check extract-code-graph.ps1 YAML frontmatter parser.'
    },
    @{
        Name      = 'Markdown section nodes extracted from Mentor.agent.md'
        Reason    = 'Section nodes anchor in-document references; missing = broken doc-drift detection.'
        Assertion = {
            $count = @($graph.nodes | Where-Object { $_.id -like 'code-section:.github/agents/Mentor.agent.md::*' }).Count
            return $count -ge 4
        }
        Hint      = 'Check extract-code-graph.ps1 markdown heading-to-section logic.'
    },
    @{
        Name      = 'TypeScript function nodes extracted from welcome.ts'
        Reason    = 'Without code-func extraction, "where is X defined" queries fail across the extension.'
        Assertion = { Test-NodeExists 'code-func:extensions/mssa-mentor/src/commands/welcome.ts::registerWelcomeCommands' }
        Hint      = 'Check extract-code-graph.ps1 TypeScript function-discovery regex.'
    },
    @{
        Name      = 'TypeScript import edges resolve to target code-files'
        Reason    = 'Cross-file dependency queries (blast-radius) depend on import nodes referencing real files.'
        Assertion = {
            # Sample: welcome.ts imports ../chatOpener; the import node should exist AND
            # the [references] edge from the import to the target code-file should resolve.
            $importId = 'code-import:extensions/mssa-mentor/src/commands/welcome.ts::../chatOpener'
            $targetFile = 'code-file:extensions/mssa-mentor/src/chatOpener.ts'
            (Test-NodeExists $importId) -and (Test-EdgeExists -Source $importId -Target $targetFile -Type 'references')
        }
        Hint      = 'Check extract-code-graph.ps1 TypeScript import resolver.'
    },
    @{
        Name      = 'PowerShell CLI tool nodes exist for the validate/ folder'
        Reason    = 'cli-tool:* nodes are how the agent discovers tools. Missing = agent forgets its toolset.'
        Assertion = {
            (Test-NodeExists 'cli-tool:validate-paths') -and
            (Test-NodeExists 'cli-tool:validate-pwsh')
        }
        Hint      = 'Check auto-discover-features.ps1 CLI-tool discovery in cli/validate/, cli/inspect/, etc.'
    },
    @{
        Name      = 'Skill nodes exist for at least one method'
        Reason    = 'skill:* nodes are how the agent selects teaching method behavior; missing = agent picks nothing.'
        Assertion = { Test-NodeExists 'skill:ride-along' -or (Test-NodeOfType -Type 'skill' -MinCount 3) }
        Hint      = 'Check auto-discover-features.ps1 SKILL.md discovery.'
    },
    @{
        Name      = 'Track nodes exist'
        Reason    = 'track:* nodes drive the cockpit picker; missing = learner has no options.'
        Assertion = {
            (Test-NodeExists 'track:cloud-app-dev') -or (Test-NodeOfType -Type 'track' -MinCount 3)
        }
        Hint      = 'Check auto-discover-features.ps1 track discovery in .github/skills/tracks/.'
    },
    @{
        Name      = 'Extension node exists and contains its source files'
        Reason    = 'extension:* node is the bridge from agent system to extension code; if it lost its [contains] edges, blast-radius queries break.'
        Assertion = {
            (Test-NodeExists 'extension:mssa-mentor') -and (Test-ChildNodes -ParentId 'extension:mssa-mentor' -MinCount 5)
        }
        Hint      = 'Check auto-discover-features.ps1 extension discovery (package.json walker).'
    },
    @{
        Name      = 'Behavior numbering sequence has no gaps below 30'
        Reason    = 'Hand-authored behaviors are numbered. Gaps suggest a behavior got dropped during auto-discover.'
        Assertion = {
            # Skip 1 known gap (we use behavior:01-15 then jump to 16-21 etc — pin >=15 distinct)
            $count = @($graph.nodes | Where-Object { $_.id -match '^behavior:\d{2}-' }).Count
            return $count -ge 15
        }
        Hint      = 'Check auto-discover-features.ps1 or extract — behaviors may have lost their nodes.'
    },
    @{
        Name      = 'Entry-point nodes exist (added 2026-06-04 for greeting fix)'
        Reason    = 'These nodes model how the agent is invoked. They are the answer to the greeting bug.'
        Assertion = {
            (Test-NodeExists 'entry-point:user-typed') -and (Test-NodeExists 'entry-point:extension-seed')
        }
        Hint      = 'These are hand-authored in mentor-graph.json; check merge.ps1 did not strip them.'
    },
    @{
        Name      = 'Purpose node exists and 100% linkage holds'
        Reason    = 'purpose:mentor is the Meadows leverage-point anchor; loss breaks the purpose-linkage audit.'
        Assertion = { Test-NodeExists 'purpose:mentor' }
        Hint      = 'Hand-authored; check it was not pruned in a merge.'
    },
    @{
        Name      = 'Test nodes exist for major skills'
        Reason    = 'test:* coverage is how confidence scoring lifts nodes from medium to high.'
        Assertion = { Test-NodeOfType -Type 'test' -MinCount 5 }
        Hint      = 'Check auto-discover-features.ps1 test discovery in tests/ and *.test.md.'
    }
)

# Run pins.
$results = [System.Collections.Generic.List[object]]::new()
foreach ($pin in $pins) {
    $passed = $false
    $errMsg = $null
    try {
        $passed = [bool](& $pin.Assertion)
    } catch {
        $errMsg = $_.Exception.Message
    }
    $results.Add([pscustomobject]@{
        Name   = $pin.Name
        Passed = $passed
        Error  = $errMsg
        Reason = $pin.Reason
        Hint   = $pin.Hint
    })
}

$passedCount = @($results | Where-Object { $_.Passed }).Count
$failedCount = @($results | Where-Object { -not $_.Passed }).Count

if ($Quiet) {
    Write-Host "Extractor stability: $passedCount / $($pins.Count) pins held"
    if ($failedCount -gt 0) { exit 1 } else { exit 0 }
}

Write-Host ""
Write-Host "=== Extractor Stability Pins ===" -ForegroundColor Cyan
Write-Host ""

foreach ($r in $results) {
    if ($r.Passed) {
        Write-Host "  PASS  $($r.Name)" -ForegroundColor Green
    } else {
        Write-Host "  FAIL  $($r.Name)" -ForegroundColor Red
        Write-Host "        why    : $($r.Reason)" -ForegroundColor DarkGray
        Write-Host "        hint   : $($r.Hint)" -ForegroundColor DarkGray
        if ($r.Error) {
            Write-Host "        error  : $($r.Error)" -ForegroundColor DarkRed
        }
    }
}

Write-Host ""
Write-Host "Summary: $passedCount / $($pins.Count) pins held" -ForegroundColor $(if ($failedCount -gt 0) { 'Red' } else { 'Green' })
Write-Host ""

if ($failedCount -gt 0) { exit 1 } else { exit 0 }
